### ISSUE TITLE
Cannot reach HTTPS url with SOAPEngine.requestUrl

### ISSUE THREAD

**Issue by andrerinaldi** [priore/SOAPEngine#181]
Hi,

I'm calling SOAPEngine.requestUrl with an **https** url. 
At this URL there's a Microsoft .NET Web Service which gives back a valid WSDL.

The library works fine with **http** urls, so I was wondering if there's something more I need to do in order to support **https** urls.

Thank you for your attention!

**Comment by priore** [comment]
Not nothing to add, look the paypal or magento [samples](https://github.com/priore/SOAPEngine#how-to-use), check if your network 443 is accessible, check if the xcode [transport security](https://github.com/priore/SOAPEngine#security-for-xcode-8x-or-later) is set correctly even for https protocols, or you provide us an url to do a test for you.

note: If you want to make the communications even safer we suggest to use of the certified pinning method, but you need to provide a certificate to the client (or maybe your server already provides pinning and that's why you can't communicate in https?)
