### ISSUE TITLE
Xcode 11 (Beta) Compatibility

### ISSUE THREAD

**Issue by ChrisMarshallNY** [priore/SOAPEngine#198]
Howdy, this is the same guy as "LittleGreenViper." I have changed that to an organizational account, and am using a personal account for my general GitHub work.

It is very limited as to what I can discuss, as Apple is strict about discussion of prerelease software, but I am having code-signing issues with the new beta Xcode 11.

Have you had a chance to test against Xcode 11?

**Comment by ChrisMarshallNY** [comment]
Just FYI. It looks like I had to re-enter "--deep" into the "Other Code Signing Flags" setting in the Build Settings for my Mac target. I still have a lot of testing to do, but that helped me to move past this blocker.
The new Xcode is still a bit shaky, but it probably wouldn't be a bad idea to test against it.

**Comment by priore** [comment]
Hello Chris,
we have not yet tested with Xcode 11, also because it is in beta and we prefer stable versions, many previous versions of Xcode beta gave errors not derived from the code developed, for many others codes, but as soon as a stable Xcode 11 version comes out we will be the first to move to this new version and also to check the functioning of our code.

We thank you very much for your report, you are always welcome.
Support Team

**Comment by ChrisMarshallNY** [comment]
Understand perfectly. I can report that I now have it working as it worked before, with the new Xcode version.
