### ISSUE TITLE
Is SSL supported?

### ISSUE THREAD

**Issue by jaunesarmiento** [priore/SOAPEngine#34]
I'm trying to use SOAPEngine for a web service that runs on SSL and I'm getting the following error:
`The operation couldn't be completed. (NSURLErrorDomain error -1012.)`.

Removing `https` and replacing it with just `http` works.

**Comment by priore** [comment]
The SOAPEngine supports https, the error -1012 happens when the site requires authentication, usually basic authentication, or the server have an invalid certificate. In the first case, for a basic authentication, sets the property named authorizationMethod and property named username and property name password, in the second case, the server have a invalid certificate, set the property named selfsigned.
If you prefer to send us the url that you use and we'll give you a working example.

**Comment by jaunesarmiento** [comment]
I'm using the ResDiary API. My client is on NDA so I won't be able to disclose much information about it. But it doesn't say in their documentation that they're requiring basic authentication and they have a separate login API endpoint. I'll try the `selfsigned` property and see if that works.

Thanks for the prompt reply! :)
